name: xmonad-config
version: 0.1.0.0
author: "sproott"

ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints -O2 -j -dynamic

dependencies:
  - base >= 4.7 && < 5
  - xmonad-contrib

source-dirs: src

executables:
  xmonad:
    main: xmonad.hs
    dependencies:
      - xmonad
      - containers
      - X11
  xmobar:
    main: xmobar.hs
    dependencies:
      - xmobar
    ghc-options: -rtsopts -threaded -with-rtsopts=-N
