# Inserts a blank line between shell prompts
add_newline = true

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
