[font]
size = 10

[font.normal]
family = "monospace"

[keyboard]
bindings = [
  { key = "Escape", mods = "Shift", action = "ToggleViMode" },
  { key = "D", mods = "Alt", action = "ScrollPageDown" },
  { key = "U", mods = "Alt", action = "ScrollPageUp" },
  { key = "J", mods = "Alt", action = "ScrollLineDown" },
  { key = "K", mods = "Alt", action = "ScrollLineUp" },
  { key = "J", mods = "Alt|Shift", action = "DecreaseFontSize" },
  { key = "K", mods = "Alt|Shift", action = "IncreaseFontSize" },
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
]

[selection]
save_to_clipboard = false

[window]
opacity = 0.95

[general]
import = [
  "~/.config/alacritty/themes/alacritty_0_12.toml"
]
